
@startuml
actor test_runner #blue
participant test_suite
participant sut
participant database
participant foo_shuffled
participant foo

test_runner -> test_suite: execute
test_suite -> sut: execute
sut -> database : SELECT * FROM \nfoo_shuffled INNER JOIN (..)
database -> foo_shuffled: SELECT *
foo_shuffled -> foo : SELECT * ORDER BY random()
foo -> foo_shuffled : [2,1,3]
foo_shuffled -> database : [2,1,3]
database -> sut: [2,1,3]
sut -> test_suite : [2,1,3]
test_suite -> test_runner : 1 test failed, \n expected [1, 2, 3] but was [2,1,3]
@enduml
