version: '3.7'

services:

  database:
    image: postgres:alpine
    container_name: ${DATABASE_INSTANCE_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_INSTANCE_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DATABASE_PORT}:5432

