services:

   postgresql:
      image: postgres:${POSTGRESQL_IMAGE_VERSION}
      container_name: concurrency
      ports:
         - "${POSTGRESQL_EXPOSED_PORT}:${POSTGRESQL_INTERNAL_PORT}"
      environment:
         POSTGRES_USER: ${POSTGRESQL_SUPERUSER_USERNAME}
         POSTGRES_PASSWORD: ${POSTGRESQL_SUPERUSER_PASSWORD}
         POSTGRES_DB: ${POSTGRESQL_SUPERUSER_DATABASE_NAME}
      #    https://www.postgresql.org/docs/current/app-postgres.html
      command: postgres -c shared_preload_libraries='pg_stat_statements' -c log_statement='all' -c log_min_duration_statement=0 -c max_connections=${POSTGRESQL_MAX_CONNECTIONS}
      healthcheck:
         test: "psql --dbname \"host=localhost port=${POSTGRESQL_INTERNAL_PORT} dbname=${POSTGRESQL_SUPERUSER_DATABASE_NAME} user=${POSTGRESQL_SUPERUSER_USERNAME} password=${POSTGRESQL_SUPERUSER_PASSWORD}\""
         interval: 1s
         timeout: 10s
         retries: 20
      deploy:
         resources:
            limits:
               cpus: '${POSTGRESQL_CPU_COUNT}'
               memory: 1G
